### ISSUE TITLE
Foreign Keys don't work

### ISSUE THREAD

**Issue by Lewiky** [TempleEight/temple#289]
Minimal example:
```
Foreign: project{
  #language(go);
  #database(postgres);
  #provider(dockerCompose);
}

Foo: service {
  field: int;
  bar: Bar;
}

Bar: service {
  test: int;
}
```

When trying to create a new `Foo`, you first need to create a new `Bar`. This works fine, but the CREATE on the `Foo` checks for the existence of the `Bar`, which comes back as negative, even though the `Bar` does exist, running a manual `GET` to the `/api/bar/{UUID}` endpoint returns the expected result.

**Comment by jaylees14** [comment]
I have a feeling this is due to the updates to the `ID` key being decapitalised in the response. I should have a fix coming shortly.

**Comment by jaylees14** [comment]
The ID key didn't fix this - looks like a Go issue rather than `temple test`. Handing off to @Lewiky

**Comment by willjvsmith** [comment]
@Lewiky is working on the kong script gen for non-auth projects, so I'm gonna work on this issue
